name: CI

on: push

jobs:
  commit-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Checkout latest commit

    - name: Set up Docker Compose
      run: docker compose -f docker-compose.cicd.yml up -d --build

    - name: Install Composer dependencies
      run: docker exec queuer-php-fpm composer install --no-interaction
    
    - name: Run PHPStan
      run: docker exec queuer-php-fpm vendor/phpstan/phpstan/phpstan

    - name: Run PHP-CS-Fixer
      run: docker exec queuer-php-fpm vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run --diff --allow-risky=yes --verbose --show-progress dots